controller:
  replicaCount: 1
  controllerOnly: false

image:
  repository: bitnamilegacy/kafka
  tag: 3.5.2-debian-11-r0

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT