apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-web
  namespace: homework
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi