apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-app
  namespace: homework
data:
  file: |
    <!DOCTYPE html>
    <html lang="ru">
      <head>
        <meta charset="UTF-8">
        <title>My First Webpage</title>
      </head>
      <body>
        <h1>Hello World!</h1>
      </body>
    </html>