apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: homework
spec:
  initContainers:
    - name: downloadPageHtml
      image: busybox:1.28
      command:
      - wget
      - "-O"
      - "/init/index.html"
      - https://awakeagency.webflow.io
      volumeMounts:
      - name: workdir
        mountPath: "/init"
  containers:
  - name: nginx
    image: nginx:lastest
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","rm -rf /usr/share/nginx/html/*"]
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: workdir
    emptyDir: {}
  